---
title: "Random Thoughts"
---

These are not-well-thought out thoughts about various random things. Some of these may not even survive me pressing enter and going about my day.

## Sports

::: {.takes}
- 🏀 [July 27, 2026.]{.take-date} My VOLO basketball league starts 07/28. Coed. My target: 12 PPG, 4 APG, 8 RPG, 2 BPG, 2 SPG, <2 TOPG. Will update stats here as the season goes along.
- 🏈 [July 27, 2026.]{.take-date} This is my year for fantasy football!! My main leagues are one fantasy and one redraft league&hellip;I think I can win both this year (irrelevant, but I have said this every year and have never won, but also never gotten last place &mdash; #NoLastPlacePunishment).
- 🏀 [July 27, 2026.]{.take-date} I'm not sure I'm a fan of LeBron going to Philly. My prediction is that there will be a lot of personality clashes on this team. Another is that there will be 0 playoff games where both LeBron and Embiid are playing.
- 🏀 [July 27, 2026.]{.take-date} Feel so lucky to be living in NY (East Village) for the Knicks championship run! Fun fact, I skipped a solid mechanics exam in undergrad (no regrets) to see Jalen Brunson, Mikal Bridges, and Josh Hart (and Donte DiVincenzo, etc.) and Villanova in the Final Four in 2018, where they broke the 3pt record and won the championship! Full circle!
- 🏀 [July 27, 2026.]{.take-date} While the Luka trade is just abysmal, as a Mavs fan, I'm coming around to the perspective that Luka is unlikely to be the best player on a championship team unless you just surround him with only 3-and-D guys and a lob threat/elite rim protector&hellip;possible, but hard to get such a team together.
:::

## Film

::: {.takes}
- 🎬 [July 27, 2026.]{.take-date} I saw The Odyssey (originally had 2:50 AM tickets, but got 6 AM tickets luckily!). Really liked it, but I'm not sure I was as big a fan as I could have been. I think my Nolan pyramid may be:<br>[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Oppenheimer<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Dark Knight&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;Interstellar<br>Tenet&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Inception&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Odyssey<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&hellip;]{.take-pyramid}Special consideration for The Prestige and The Dark Knight Rises.
:::
